fixed bug: an undefined cooldown would cause an error
In worldunit.py, line 639, in aim:
TypeError: unsupported operand type(s) for +: int and NoneType